import { accountPortugueseCopy } from './account-portuguese-copy'
import { workspacePortugueseCopy } from './workspace-portuguese-copy'

export const portugueseCopy: Readonly<Record<string, string>> = {
  ...accountPortugueseCopy, ...workspacePortugueseCopy,
  'Event categories': 'Categorias de eventos', 'Next up': 'A seguir', 'item': 'compromisso', 'items': 'compromissos',
  'Public events currently cover São Paulo, from the official SP Mais Cultura agenda.': 'A agenda pública cobre São Paulo, com eventos da agenda oficial SP Mais Cultura.',
  'Language': 'Idioma', 'Switch to light mode': 'Ativar tema claro', 'Switch to dark mode': 'Ativar tema escuro', 'Light': 'Claro', 'Dark': 'Escuro',
  'Upcoming events': 'Próximos eventos', 'Saved events': 'Eventos salvos', 'City': 'Cidade', 'Event or keyword': 'Evento ou palavra-chave',
  'Good things, closer to home': 'Boas descobertas, perto de você', 'Out there.': 'Lá fora.', 'For you.': 'Para você.',
  'Discover your next plan, just around the corner.': 'Encontre seu próximo programa, logo ali.', 'Your preferences': 'Suas preferências',
  'Picked for your interests:': 'Seus interesses:', 'Free events first': 'Gratuitos primeiro', 'Paid experiences first': 'Experiências pagas primeiro', 'All budgets welcome': 'Para todos os bolsos',
  'Music': 'Música', 'Arts': 'Artes', 'Food': 'Gastronomia', 'Outdoors': 'Ao ar livre', 'Technology': 'Tecnologia', 'Sports': 'Esportes',
  'music': 'Música', 'arts': 'Artes', 'food': 'Gastronomia', 'outdoors': 'Ao ar livre', 'technology': 'Tecnologia', 'sports': 'Esportes',
  'Music, art, a little adventure…': 'Música, arte, uma nova experiência…', 'e.g. São Paulo': 'Ex.: São Paulo', 'All cities': 'Todas as cidades',
  'Using selected location': 'Localização selecionada', 'Distance': 'Distância', 'Searching…': 'Buscando…', 'Find events': 'Buscar eventos',
  'Category': 'Categoria', 'All categories': 'Todas as categorias', 'Price': 'Preço', 'All prices': 'Todos os preços', 'Free only': 'Somente gratuitos', 'Paid only': 'Somente pagos',
  'From date': 'A partir de', 'To date': 'Até', 'Sort by': 'Ordenar por', 'Best matches': 'Mais relevantes', 'Soonest first': 'Mais próximos no tempo', 'Nearest first': 'Menor distância', 'Lowest price': 'Menor preço', 'Clear filters': 'Limpar filtros', 'More filters': 'Mais filtros',
  'Finding your location…': 'Buscando sua localização…', 'Use my location': 'Usar minha localização', 'Finding cities…': 'Buscando cidades…', 'Find city on map': 'Localizar cidade no mapa',
  'Use GPS or choose a city to search by distance. Location is requested only when you choose.': 'Escolha uma cidade ou use o GPS para buscar por distância. Você decide quando compartilhar a localização.',
  'No matching cities. Try a city and country, or search the catalog directly.': 'Nenhuma cidade encontrada. Tente cidade e país ou digite a cidade manualmente.',
  'Choose your city to search nearby:': 'Escolha a cidade:', 'City data by': 'Dados de cidades por', 'Your current location': 'Sua localização atual',
  'Enter a city with at least two characters.': 'Digite pelo menos dois caracteres para buscar uma cidade.',
  'Looking for your next plan…': 'Buscando seu próximo programa…', 'Finding your neighborhood…': 'Encontrando sua região…', 'Finding your city…': 'Encontrando sua cidade…',
  'No upcoming events found.': 'Nenhum próximo evento encontrado.', 'No saved events match these filters.': 'Nenhum evento salvo corresponde aos filtros.',
  'Save an event or clear your filters to see more plans.': 'Salve um evento ou limpe os filtros para ver mais opções.',
  'Try another city, a wider radius, or fewer filters. New events appear when they’re added to the catalog.': 'Tente outra cidade, amplie a distância ou remova alguns filtros.',
  '{count} found': '{count} encontrados', 'A new plan starts here': 'Seu próximo programa começa aqui',
  'Price not listed': 'Preço não informado', 'Free': 'Gratuito', 'Event details': 'Detalhes do evento', 'Official agenda': 'Agenda oficial', 'Source: {source}': 'Fonte: {source}',
  'Matches your interests': 'Combina com você', 'Save': 'Salvar', 'Saved': 'Salvo', 'In agenda': 'Na agenda', 'Add to agenda': 'Adicionar à agenda', 'Map': 'Mapa',
  'Save {title}': 'Salvar {title}', 'Unsave {title}': 'Remover {title} dos salvos', 'Add {title} to agenda': 'Adicionar {title} à agenda', 'Added {title} to agenda': '{title} adicionado à agenda', 'View {venue} on map': 'Ver {venue} no mapa',
  'Showing up to 100 matches. Narrow your keyword, dates or distance for more specific results.': 'Mostrando até 100 resultados. Refine a busca, as datas ou a distância para ver mais opções.',
  'Your search location': 'Localização da busca', 'Your search area · {radius} km': 'Sua região de busca · {radius} km', 'Selected city': 'Cidade selecionada',
  'View search area on OpenStreetMap': 'Ver região da busca no OpenStreetMap', 'View map': 'Ver mapa', 'Clear location': 'Limpar localização',
  'Approximate coordinates are shared with Open-Meteo for current weather.': 'Coordenadas aproximadas são enviadas ao Open-Meteo para consultar o clima atual.',
  'Weather is unavailable right now.': 'O clima está indisponível no momento.', 'Loading local weather…': 'Carregando o clima…', 'Weather by Open-Meteo': 'Clima por Open-Meteo', 'now': 'agora',
  'Clear sky': 'Céu limpo', 'Cloudy': 'Nublado', 'Foggy': 'Neblina', 'Rainy': 'Chuva', 'Snowy': 'Neve', 'Thunderstorms': 'Tempestades', 'Current conditions': 'Condições atuais',
  'Suggested cities': 'Cidades sugeridas', 'You can enter a city manually and keep searching.': 'Você pode digitar a cidade manualmente e continuar buscando.',
  'Discover': 'Explorar', 'Events worth making time for.': 'Eventos que merecem seu tempo.', 'Explore the city.': 'Explore a cidade.', 'Make a little room.': 'Abra espaço para algo novo.',
  'Browse real events. Sign in to save your favorites and organize your day.': 'Descubra eventos reais. Entre para salvar favoritos e organizar seu dia.',
  'Public agenda · São Paulo': 'Agenda pública · São Paulo', 'Events from the official SP Mais Cultura agenda. More cities are available in our catalog.': 'Eventos da agenda oficial SP Mais Cultura. Outras cidades estão disponíveis no nosso catálogo.',
  'Explore events': 'Explorar eventos', 'Back to events': 'Voltar aos eventos', 'Close sign-in': 'Fechar acesso à conta', 'Sign in to save your plans': 'Entre para salvar seus planos',
  'Loading upcoming events…': 'Carregando próximos eventos…', 'Public events are unavailable right now. Please try again.': 'Os eventos públicos estão indisponíveis agora. Tente novamente.',
  'Try again': 'Tentar novamente', 'Search all events': 'Ver todos os eventos', 'No events match your search.': 'Nenhum evento corresponde à busca.',
  'Clear the keyword or filters to explore more events.': 'Limpe a palavra-chave ou os filtros para descobrir mais eventos.',
  'Saved for this session. Browser storage is unavailable.': 'Salvo nesta sessão. O armazenamento do navegador está indisponível.',
  'Event search is unavailable right now. Please try again shortly.': 'A busca de eventos está indisponível agora. Tente novamente em instantes.',
  'Event search is not connected yet. Please contact the site owner.': 'A busca de eventos ainda não está conectada. Entre em contato com o responsável pelo site.',
  'Choose a search radius between 1 and 100 km.': 'Escolha uma distância entre 1 e 100 km.', 'Your location could not be read. Try entering a city instead.': 'Não foi possível ler sua localização. Digite uma cidade.',
  'Enter a city or use your current location.': 'Digite uma cidade ou use sua localização atual.', 'Keep your search under 120 characters.': 'Use até 120 caracteres na busca.',
  'Choose a valid event date.': 'Escolha uma data válida.', 'The end date must be on or after the start date.': 'A data final deve ser igual ou posterior à data inicial.',
  'Location is unavailable in this browser. Enter a city instead.': 'A localização não está disponível neste navegador. Digite uma cidade.', 'Location access was denied. Enter a city to search.': 'O acesso à localização foi negado. Digite uma cidade para buscar.', 'Your location could not be found. Try again or enter a city.': 'Não foi possível encontrar sua localização. Tente novamente ou digite uma cidade.',
}
